const LADDER = [
    "Hauk liker pizza.",
    "Manu kjøpte en ny vin.",
    "Stig elsker å drikke øl.",
    "Aboveit er selskapet vårt.",
    "Hauk danser som en stjerne.",
    "AI er virkelig fascinerende.",
    "Manu synger alltid i dusjen.",
    "Vi elsker AI, spesielt i dag.",
    "Stig og Manu delte en øl i går.",
    "Stig spiller fotball med vennene.",
    "Hauk danset på bordet i går kveld.",
    "Aboveit lager den beste ølen i byen.",
    "Hauk mistet vinen sin i parken i går.",
    "Manu vant førsteprisen i vinlotteriet.",
    "AI hjalp Stig med fotballtreningen hans.",
    "Manu glemte å kjøpe øl til festen i går.",
    "AI hjelper Hauk med sjakk, og han blir bedre.",
    "Stig prøvde å spille gitar, men feilet miserabelt.",
    "Aboveit vinner på alle områder med sin fantastiske AI.",
    "Manu synger karaoke med vin, og det er alltid en fest.",
    "Hauk og Manu tok en vinpause under arbeidet på Aboveit.",
    "Stig og Hauk delte en øl etter fotballkampen i går kveld.",
    "AI forstår oss bedre enn Stig, det er ganske imponerende!",
    "Hauk prøver å lære AI å danse, noe som er veldig morsomt.",
    "Manu skapte en AI som elsker vin, noe som er helt utrolig.",
    "Stig fant en AI som kan brygge øl, og vi er alle imponerte.",
    "Manu spiser pizza med vin, en uvanlig men deilig kombinasjon.",
    "Aboveit lager den beste AI-en, og vi er veldig stolte av det.",
    "Stig er bedre i AI enn fotball, men han prøver fortsatt hardt.",
    "Hauk og Stig lærte AI å spille sjakk med vin, og det ble en stor suksess."
]

export default LADDER;